import type {Metadata} from "next";
import Navigation from "../components/Navigation";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jon David Painting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative w-full">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
